### ISSUE TITLE
Add more keywords to emoji that has only one keyword

### ISSUE THREAD

**Issue by muan** [muan/emoji#11]

**Comment by strongme** [comment]
can anyone tell me how to use this amazing tool?

**Comment by Roemerb** [comment]
Picking this up if you can authenticate me to make commits. All emoji's will have at least two keywords :) commiting today or tomorrow

**Comment by jordanrobinson** [comment]
The following handy regex lets you see which emoji still only have one keyword: `^[^,]*,[^,]*$`

**Comment by alfredxing** [comment]
@Roemerb You can fork the repository (there should be a button near the top-right of the page), then commit to your fork and submit pull requests). See https://guides.github.com/activities/forking/ for more instructions :octocat:

**Comment by PatrickRed** [comment]
@alfredxing 
Hi, I am new to gitHub but I am familiar with pulling. My problem is what language is this actually written and which file contains the source code for the emoji indexes so I could possibly make a version using espanol?

Also what tools would I need to test this project?

**Comment by alfredxing** [comment]
All of the emoji data is stored in `emojis.json`, which is written in JSON. The rest of the site should be written in HTML, CoffeeScript, and SCSS. You'll need a local web server to test it out, but other than that, I don't think any special tools are required if you're just changing `emojis.json`. If you want to change any of the SCSS or CoffeeScript files, you'll need compilers to turn them into CSS and JS.

I suggest that you ask @muan about whether or not she wants Spanish localization though.

**Comment by aalfredob2014** [comment]
nesecito español por me comen las comunidades

2014-11-04 6:16 GMT-03:00 PatrickRed notifications@github.com:

**Comment by davefp** [comment]
@PatrickRed It looks like @muan is open to including localizations in new JSON files. See #68 for more info.

I imagine spanish would sit in `emojis_es.json` so start a PR with that file and you should be good to go!

**Comment by muan** [comment]
We've gone a long way. Here's a list of the remaining emoji that only has one keyword:
1. :poop: `poop`
2. :arrow_backward: `arrow_backward`
3. :arrow_double_down: `arrow_double_down`
4. :arrow_double_up: `arrow_double_up`
5. :arrow_down: `arrow_down`
6. :arrow_down_small: `arrow_down_small`
7. :arrow_forward: `arrow_forward`
8. :arrow_heading_down: `arrow_heading_down`
9. :arrow_heading_up: `arrow_heading_up`
10. :arrow_lower_left: `arrow_lower_left`
11. :arrow_lower_right: `arrow_lower_right`
12. :symbols: `symbols`
13. :diamond_shape_with_a_dot_inside: `diamond_shape_with_a_dot_inside`
14. :flower_playing_cards: `flower_playing_cards`
15. :six_pointed_star: `six_pointed_star`
16. :small_red_triangle: `small_red_triangle`
17. :small_red_triangle_down: `small_red_triangle_down`
