### ISSUE TITLE
Failed to load emoji.png resource when testing

### ISSUE THREAD

**Issue by wenqinYe** [muan/emoji#111]
I'm having issues testing. The emoji.png resource is not loading, and the error message given is: The requested URL was not found no the server.

**Comment by muan** [comment]
You'll need to use the [`rake` command](https://github.com/muan/emoji/blob/gh-pages/Rakefile#L4-L6) to build the site for development. Did you do that and it errors?

**Comment by wenqinYe** [comment]
Whoops forgot to do that, thank you.
