### ISSUE TITLE
Missing :fu: emoji from CSS

### ISSUE THREAD

**Issue by ChrisMBarr** [muan/emoji#121]
In the demo th `:fu:` (:fu:) shows up as the `:thumbsdown:` (:thumbsdown:) emoji since the `s_fu` CSS class [apparently does not exist](https://github.com/muan/emoji/blob/gh-pages/stylesheets/emoji.css#L332), yet the `"fu"` item [is defined in the json file](https://github.com/muan/emoji/blob/gh-pages/emojis.json#L885).

![emoji-fu](https://cloud.githubusercontent.com/assets/463685/5825799/2014dd96-a0bc-11e4-8f42-4a6c1e9d0c90.png)

i did a quick manual look over of [the image sprite](https://raw.githubusercontent.com/muan/emoji/gh-pages/emoji.png), and I did not see the :fu: icon.  I may have missed it though...

---

On the [demo page](http://emoji.muan.co/), you can run the following bit of code in the JS console to return all the emoji classes that have a default background position of `0px 0px` or `0% 0%`

```
$(".emoji").filter(function(){
  return $(this).css("backgroundPosition").replace(/px|%/g,"") == "0 0"
}).each(function(){
  console.log($(this).attr("class").replace("emoji ",""))
});
```

**Comment by muan** [comment]
Heh. You are right, thanks for reporting this and the handy snippet. Should be fixed now. :grimacing:

**Comment by ChrisMBarr** [comment]
Excellent thanks!  :+1:
