### ISSUE TITLE
能不能加一個 可愛的 蟬[cicada] 的 emoji  ^-^

### ISSUE THREAD

**Issue by xieyuheng** [muan/emoji#123]
能不能加一個 可愛的 蟬[cicada] 的 emoji  ^-^
因爲 我正在設計一個叫 蟬語[cicada-language] 的程序語言

**Comment by muan** [comment]
這個 repository 只是用來幫現有的 emoji 增加 keywords 而已，沒有辦法新增 emoji 唷。

**Comment by fvck** [comment]
# 测试一下  怎么  用 :1234:

好棒
