### ISSUE TITLE
Shift+click to copy multiple

### ISSUE THREAD

**Issue by muan** [muan/emoji#134]
Now that the queue feature is gone, I find myself wanting to copy multiple emoji but has no way of doing so. :cry:

**Comment by mrzmyr** [comment]
How about using [`pbcopy`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/pbcopy.1.html) ?

**Comment by muan** [comment]
This project is a webpage, what do you mean?

**Comment by mrzmyr** [comment]
😶Woops, my head still stuck in the emojilib repo. 
So, you want to select multiple emojis and copy them ?

**Comment by muan** [comment]
Currently click copies one, so with this, if you shift + click another, it'll just append another emoji code to your clipboard instead of just copying another.

**Comment by mrzmyr** [comment]
There you go #153 :shipit: :grin:

**Comment by linking2014** [comment]
hi :smiley:

**Comment by linking2014** [comment]
test :fearful:

**Comment by linking2014** [comment]
test again ✈

**Comment by Jian881219** [comment]
:joy:

**Comment by mrzmyr** [comment]
Any updates on this ?
cc @muan

**Comment by cls1991** [comment]
:kissing_heart:

**Comment by ghost** [comment]
I am having the test on it as well. One moment as I make sure it will again work.

**Comment by lookphp** [comment]
travlling?

**Comment by ryanlid** [comment]
:trollface:

**Comment by wangjian88** [comment]
:rofl:京津冀:grin:

**Comment by lookphp** [comment]
😢 💯 🥇 🔢
