### ISSUE TITLE
Too many thumbs down

### ISSUE THREAD

**Issue by IonicaBizau** [muan/emoji#159]
See the screenshots. :sob: 

![image](https://cloud.githubusercontent.com/assets/2864371/12701341/69038108-c80f-11e5-925b-19b51d7bb999.png)

![image](https://cloud.githubusercontent.com/assets/2864371/12701342/6ca1dd64-c80f-11e5-8dfd-84c08298adc0.png)

**Comment by muan** [comment]
This happens because 1. it seems like you don't have `AppleColorEmoji` so it uses the sprite 2. the sprite does not include those new emojis. I've _fixed_ it so that they won't be :-1:, by defaulting them to blank. However, it's still not ideal. Can you view the new unicode emojis on your OS?

**Comment by IonicaBizau** [comment]
@muan Oh, got it! Thanks for the fix. They now look blank.
Aren't these new emojis available as images, like the others?

![image](https://cloud.githubusercontent.com/assets/2864371/12739394/16253c9c-c972-11e5-8089-91a8ac5bbd8c.png)
