### ISSUE TITLE
Missing Emoji

### ISSUE THREAD

**Issue by ivavictoria** [muan/emoji#160]
Some emoji seem to have disappeared! See the screenshot below:
![missingemoji](https://cloud.githubusercontent.com/assets/4721200/12987512/693193ea-d0ca-11e5-954f-4340117013c5.PNG)

**Comment by muan** [comment]
Soooooo, those are the new emojis, and they're not available in image forms. Are you on Windows? If you can view native emoji somehow we can find a condition to switch to native [here](https://github.com/muan/emoji/blob/0312c15195e745fd3d207f39ac2f006f20abc56b/javascripts/stuff.js#L53).

**Comment by ivavictoria** [comment]
Yes, I saw this on my work computer, which runs Windows. As far as I can tell, I can view native emoji.
I haven't checked it out on my Mac at home; I assume it's working fine there. :P

**Comment by IonicaBizau** [comment]
@muan Maybe we could take these images from http://emojipedia.org/? Maybe GitHub should fix that too (probably in [this](https://github.com/github/gemoji) repository). For example, `:scales:` should be rendered like <img height="20" src="http://emojipedia-us.s3.amazonaws.com/cache/e8/22/e8229ec7db4c2c26c7f62c664ba51c4e.png"> (:arrow_left: image is coming from emojipedia).

Not quite sure about the copyright stuff, tho... :thought_balloon:

**Comment by muan** [comment]
Yeah, mostly because of copyright stuff I'd prefer to not produce more emoji assets. We might have to use Noto Emoji instead. :grimacing:

**Comment by IonicaBizau** [comment]
@muan But Apple emojis are cooler, because GitHub uses them. :smile: What I don't understand is: why we/GitHub _can_ use these older images (e.g. `:grin:` :arrow_right: :grin:) but not the new ones (e.g. `:thinking:`)?

**Comment by muan** [comment]
@IonicaBizau afaik we are hoping to move towards using native emojis instead of any particular system.

**Comment by muan** [comment]
I am inclined to just remove the sprite implementation, and let people's browser/OS handle the emoji. 😔

**Comment by muan** [comment]
Also fun fact, Noto Emoji does not have the new emojis either.

**Comment by IonicaBizau** [comment]
>  afaik we are hoping to move towards using native emojis instead of any particular system.

That would be so sad... I was thinking few days ago to give you an idea: replacing the native characters with Apple emoji images, to be consistent.

But now, this is sad news. :sob: 

> Also fun fact, Noto Emoji does not have the new emojis either.

The native unicode character is not available on my system (Ubuntu 15.10) either:

![image](https://cloud.githubusercontent.com/assets/2864371/13140548/6e65746e-d63b-11e5-83bb-5385727669ac.png)

**Comment by muan** [comment]
You should install an emoji font. :wink: The sadder news is how AppleColorEmoji isn't open. :)

**Comment by IonicaBizau** [comment]
@muan Maybe GitHub should convince Apple to open-source the things. :joy: 

I don't think there is an easy solution to get native colorful emoji on Linux (they may be browser extensions to replaces emojis with images, but that will not work in terminal, unless you know a solution)...

**Comment by Mottie** [comment]
We have a custom Emoji userscript which includes a bunch of image and text emojis by default; and, it allows you to add your own. Check it out if you want:

https://github.com/StylishThemes/GitHub-Custom-Emojis

It's set up to allow inserting both replacable text strings (e.g. `:_bipolar:`),  or an inline image <img title=":_ bipolar :" src="https://cloud.githubusercontent.com/assets/136959/13512241/15d8362c-e15f-11e5-8c32-35b78deb9017.gif"> 

<img title=":_excite:" src="https://cloud.githubusercontent.com/assets/136959/13559383/49d88766-e3d9-11e5-9c0c-9a958bfc03ee.gif"> Enjoy!

**Comment by kavil** [comment]
:heart_eyes:

**Comment by scakemyeranasshole** [comment]
Windows has a "fallback font" capability

**Comment by muan** [comment]
I've added twemoji for users without applecoloremoji.
