### ISSUE TITLE
hasAppleColorEmoji not working

### ISSUE THREAD

**Issue by kevin940726** [muan/emoji#170]
I think this [line](https://github.com/muan/emoji/blob/c5431c96b473c169e90120782f46502196c7a50d/javascripts/hasAppleColorEmoji/hasAppleColorEmoji.js#L11) will always be true since comparing two arrays will always yield not equal.

**Comment by muan** [comment]
This issue belongs in https://github.com/muan/hasAppleColorEmoji.
