### ISSUE TITLE
Does it support windows?

### ISSUE THREAD

**Issue by jhalaa** [muan/emoji#172]
Is there windows support for this plugin? And if so how do we pop up the search on git bash/ command prompt on windows?

**Comment by aalfredob2014** [comment]
*notifico la baja de el sistema github .pues estoy recibiendo la actividad
de la cuenta de usuarios que no conozco segun los terminos los abusos de el
sistema esta prohibido sera notoficado por la corte de justicia de Estados
unidos espero una solucion por parte de usted saludos *


*UTC:03:00 Argentina*
*Ariel Bazan *

2017-07-14 8:55 GMT-03:00 Jhalaa Chinoy <notifications@github.com>:

**Comment by StoneCode5** [comment]
:frowning_face:
