### ISSUE TITLE
set font-size: 100px，emoji in android disappeared

### ISSUE THREAD

**Issue by little93** [muan/emoji#175]
Hello, I have a issue ,Would you mind give me some help?
I used emojilib in React and node; if I set "font-size: 100px" in my less file,the emoji can't show in Android mobile phone, but it can show in Iphone. Somebody could help me?

**Comment by muan** [comment]
This is a known bug in Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=625191&q=emoji%20px&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
