### ISSUE TITLE
Thoughts: 20 questions search? Other kinds of UI?

### ISSUE THREAD

**Issue by mofosyne** [muan/emoji#178]
This would be an interesting exercise in UI for emoji searchs, especially in a smartphone context.

## 20 Questions

You can get a large search space with specially crafted questions asking yes or no. This is good for small screens like say an apple watch.

## Emotion wheel

Windows comic chat has an interesting UI that allows for selecting based on emotions and intensity of.

![bb727079 assoc04_big l en-us](https://user-images.githubusercontent.com/827793/35767059-8a11677c-0938-11e8-8c96-397bac901ad1.gif)

It might not work as well for finding non-emotive icons like house etc... But the wheel can be used if icons can be arranged by regions of a wheel.

**Comment by muan** [comment]
Out of the scope of this repo :)
