### ISSUE TITLE
Connection is Not Secure warning

### ISSUE THREAD

**Issue by camlloyd** [muan/emoji#180]
🔒 Could you use HTTPS (everywhere)?
✅ You already have a valid certificate!

**Comment by muan** [comment]
Perhaps? Did this work?

**Comment by camlloyd** [comment]
@muan Yes, thank you! But wait, don't forget the links in the README! 🔗

**Comment by muan** [comment]
ty! bd9528b68410e28aa1bbc8d164c3f2165bf98ce7
