### ISSUE TITLE
Question about if statement in search function.

### ISSUE THREAD

**Issue by bdlowery** [muan/emoji#185]
```javascript
function search (keyword) {
  keyword = typeof keyword === 'undefined' ? '' : keyword
  document.querySelector('.keyword').textContent = keyword
  keyword = keyword.trim()

  if (window.speedyKeyword !== keyword) {
    window.speedyKeyword = keyword
    for (const result of document.querySelectorAll('.result')) {
      result.hidden = keyword.length > 0 ? result.getAttribute('title').toLowerCase().indexOf(keyword.toLowerCase()) < 0 : false
    }
  }
  setRelatedDOMVisibility(keyword)
} 
```

I understand most of the function. The only part I do not understand is 

```javascript
 if (window.speedyKeyword !== keyword) {
    window.speedyKeyword = keyword
```
    
I've edited the file locally and removing this if statement doesn't have an impact on the function at all.

I'm a noob and this didn't make sense 😅

**Comment by muan** [comment]
This is so that search is only performed when the keyword is **not the same as** the last searched keyword.

If not the same:

```js
 if (window.speedyKeyword !== keyword) {
```

set the new keyword to var, and search

```js
 window.speedyKeyword = keyword
```

in the next `search()` call `window.speedyKeyword` will be the last searched keyword.
