### ISSUE TITLE
Input bar UI problem

### ISSUE THREAD

**Issue by ghost** [muan/emoji#28]
When I type into the input bar, I'm getting a problem with the cancel button, I searched for it in the code but couldn't find it anywhere.

![untitled 2](https://cloud.githubusercontent.com/assets/7027060/2932112/a9b5e192-d7ab-11e3-943d-95434368723e.png)

**Comment by muan** [comment]
Which browser/version are you using?

**Comment by ghost** [comment]
Im currently using the newest version of Safari

**Comment by muan** [comment]
Firefox

![image](https://cloud.githubusercontent.com/assets/1153134/2942026/a9e00fda-d9ae-11e3-9061-3a615695d7ce.png)

Chrome

![image](https://cloud.githubusercontent.com/assets/1153134/2942028/b31d4ad6-d9ae-11e3-81f8-8926a2dc729a.png)

Safari

![image](https://cloud.githubusercontent.com/assets/1153134/2942033/c0157696-d9ae-11e3-9773-49ea20a89c57.png)

Ew.

**Comment by ghost** [comment]
The safari bar is still somewhat cutting off the x for me

**Comment by ghost** [comment]
Isn't there a way to make a different padding for all browsers?

**Comment by muan** [comment]
[Looks like a safari bug](https://github.com/necolas/normalize.css/blob/master/normalize.css#L364), I decided to remove it instead of working around it..

**Comment by ghost** [comment]
Ok
