### ISSUE TITLE
New Emoji

### ISSUE THREAD

**Issue by alrra** [muan/emoji#39]
This month [version 7.0.0 of the Unicode Standard](http://www.unicode.org/versions/Unicode7.0.0/) has been released, adding approximately 250 new emoji. :tada:

For the full list of new emoji additions, see: http://emojipedia.org/new-emoji/
## 

@muan this is more of a heads up then an actual issue, so feel free to close it.

**Comment by muan** [comment]
:zap: super excited about this. Thanks.
