### ISSUE TITLE
`h:over` style after copied

### ISSUE THREAD

**Issue by aanoaa** [muan/emoji#4]
after click `:smile:` emoji, all emoji's `h:over` style looking `:smile:`.
but not just `:smile:` emoji.

**Comment by muan** [comment]
HI, I can not reproduce this problem, might be a browser compatibility issue, what browser are you using?

**Comment by aanoaa** [comment]
Firefox 25.0.1

yes, it looks like browser compatibility issue.
google chrome works.

**Comment by muan** [comment]
Looks like it's a zeroclipboard(https://github.com/zeroclipboard/zeroclipboard) bug, and it's been there for ages. Zeroclipboard does the copying part, without it, you'll have to manually copy things.
I was able to get it working by downloading/installing [Adobe Flash Player](http://get.adobe.com/flashplayer/) for firefox.

It not working without flash is expected, but should probably downgrade more gracefully.
