### ISSUE TITLE
Copy and paste fails silently if flash not installed

### ISSUE THREAD

**Issue by joshhunt** [muan/emoji#52]
Tried copy and paste in Safari, where I don't have Flash, and it silently failed - button was still visible and I wasn't presented with an error message.

Copy and paste behavior works as expected in Chrome (where I have Flash)

**Comment by xxmbaobao** [comment]
hi ~ i wanna make frenid wiht u

**Comment by Huoxin** [comment]
Hi,I am a software engineer, I live in Shenzhen.

From: 冯遥
Date: 2014-09-27 10:22
To: muan/emoji
Subject: Re: [emoji] Copy and paste fails silently if flash not installed (#52)
hi ~ i wanna make frenid wiht u

**Comment by muan** [comment]
This was addressed in #78 and d3fc0e5094cc00b34f9f8b95748beb5559fbeda9. Thanks for reporting!
