### ISSUE TITLE
Multilingual support?

### ISSUE THREAD

**Issue by felixonmars** [muan/emoji#67]
Hi,

I'd like to contribute to the index by adding Chinese Pinyin as indexes, so Mandarin Chinese users could search on the index much more easily.

But it would be better if there were something like an option to specify the language, so the added keywords won't disturb a typical English (as I understand is the default) user.

Some sample data:

```
"smile": ["xiaolian", "kaixin", "kuaile", "youqu", "haha"],
"blush": ["xiaolian", "weixiao", "kaixin", "kuaile", "lianhong", "haixiu"],
"fearful": ["haipa", "jinzhang", "tante"],
"angry": ["shengqi", "fennu", "fanu"],
"sleeping": ["shuijiao", "kun", "fankun"],
```

**Comment by muan** [comment]
Had a similar request previously. https://github.com/muan/emoji/pull/37#issuecomment-45462998 Feel free to create another file, called `emoji-zh-pingyin.json` perhaps. Just curious, why would you prefer searching using pingyin instead of the actual characters, which would be `emoji-zh-cn.json` instead?

**Comment by felixonmars** [comment]
Because we cannot insert the actual characters directly, so we still need to type in pinyin*, then select the correct characters. However, it's unlikely that we will enter two characters separately if they form a word, so in my opinion it makes little sense to index by the actual characters.

Just a quick example for "kaixin" (the "smile" face):

If one is searching by pinyin:
1. Type "ka" or "kai"
2. Tada! found it.

Otherwise, if one is searching by the actual Chinese characters:
1. Type "kaixin" or "kaix"
2. The input method candidate list pops up. Select the correct word "开心"
3. Found the emoji.

So you can see, searching in pinyin takes less time and the experience is more like what I expect for English :)

*: There are also other ways to input, but Pinyin remains the most popular in Simplified Chinese world.

**Comment by felixonmars** [comment]
And thanks a lot for the tip, I'll create a PR to add another file after I've done the basic parts :smile:

**Comment by muan** [comment]
Cool. I use bopomofo to input Traditional Chinese and the input method auto select the words.for me which is why using characters make more sense for me, but I can see you case. :+1:

**Comment by kaherna8** [comment]
Would having some keywords in Spanish be helpful to the multilingual part? 
I can start adding lots of keywords in Spanish..

**Comment by muan** [comment]
Any further changes to the keyword lib should be done in https://github.com/muan/emojilib. Closing.
