### ISSUE TITLE
Could you tell me the name of the homepage extension?

### ISSUE THREAD

**Issue by cirias** [muan/emoji#96]
I love the chrome homepage in the gif on the README page.
I have searched google but can't find it.
Could you tell me how can I get it? Is it made by yourself?

**Comment by muan** [comment]
It's called [**Currently**](https://chrome.google.com/webstore/detail/currently/ojhmphdkpgbibohbnpbfiefkgieacjmh?hl=en).  :)

**Comment by cirias** [comment]
Great! Thanks you.
